services:
  escola-db:
    container_name: escola-db
    build:
      context: ./db
    environment:
      POSTGRES_DB: escola
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: trust
    # ports:
    #   - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d escola"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - rede-projeto

  escola-node:
    build: ./geracao_dados
    container_name: escola-node
    depends_on:
      escola-db:
        condition: service_healthy
    environment:
      DB_HOST: escola-db
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: escola
      DB_PORT: 5432
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - rede-projeto

  escola-api:
    build: ./api
    container_name: escola-api
    ports:
      - "8000:8000"
    depends_on:
      escola-db:
        condition: service_healthy
    environment:
      DB_HOST: escola-db
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: escola
      DB_PORT: 5432
      DATABASE_URL: "postgresql://postgres:admin@escola-db:5432/escola"
    # volumes:
    #   - ./api:/app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - rede-projeto
  
  escola-frontend:
    build: ./client
    container_name: escola-frontend
    ports:
      - "3000:3000"
    depends_on:
      escola-api:
        condition: service_started
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - rede-projeto
  
  escola-nginx:
    image: nginx:1.28-alpine
    container_name: escola-nginx
    ports:
      - "8888:80"
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - nginx_logs:/var/log/nginx
      - ./server/nginx-entrypoint.sh:/nginx-entrypoint.sh
    entrypoint: ["/nginx-entrypoint.sh"]
    depends_on:
      - escola-api
      - escola-frontend
    networks:
      - rede-projeto
  

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - '4000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - grafana

  loki:
    image: grafana/loki:3.0.1
    container_name: grafana-loki
    user: "0" # To force the container to use root user and avoid permission problems
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki/loki_data:/loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    networks:
      - grafana

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - nginx_logs:/var/log/nginx/ 
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - grafana

volumes:
  grafana_data: {}
  postgres_data:
  nginx_logs:
networks:
  rede-projeto:
    driver: bridge
  grafana:
    driver: bridge
