version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: escola-db
    restart: always
    environment:
      POSTGRES_DB: escola
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  node_app:
    build: ./geracao_dados/
    container_name: escola-node
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: escola-db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: escola
      DB_PORT: 5432
    command: ["node", "gerador.js"]

volumes:
  postgres_data:
